/* eslint-disable no-template-curly-in-string */
export const listQuestion = [
  {
    id: 1,
    question: "JavaScript là ngôn ngữ xử lý ở",
    A: "Client",
    B: "Server",
    C: "Server/client",
    D: "Không có dạng nào",
    answer: "A",
  },
  {
    id: 2,
    question: "Javascript là ngôn ngữ thông dịch hay biên dịch",
    A: "Thông dịch",
    B: "Biên dịch",
    C: "Cả hai dạng",
    D: "Không có dạng nào ở trên",
    answer: "B",
  },
  {
    id: 3,
    question: "Phương thức viết chương trình của Javascript như thế nào?",
    A: "Viết riêng một trang",
    B: "Viết chung với HTML",
    C: "Cả hai dạng A và B",
    D: "Không có dạng nào.",
    answer: "C",
  },
  {
    id: 4,
    question: "Javascript là ngôn ngữ kịch bản có dấu được mã nguồn không?",
    A: "Không dấu được vì các kịch bản chạy ở client.",
    B: "Dấu được vì chương trình hoạt động độc lập với trình duyệt",
    C: "Hai phát biểu đều sai.",
    D: "Hai phát biểu đều đúng",
    answer: "A",
  },
  {
    id: 5,
    question: "JavaScript được bắt đầu bằng?",
    A: "<scritp> …</script>",
    B: "<Javascript> …<Javascript>",
    C: "<java>  </java>",
    D: "Tất cả các dạng trên.",
    answer: "A",
  },
  {
    id: 6,
    question: "Javascript có các dạng biến?",
    A: "Number, String, Boolean",
    B: "Number, Integer, char",
    C: "Number, String, Boolean, Null",
    D: "Tất cả các loại trên.",
    answer: "A",
  },
  {
    id: 7,
    question: "Trong Javascript hàm parseInt() dùng để làm gì?",
    A: "Chuyển một chuỗi thành số",
    B: "Chuyển một chuỗi thành số nguyên",
    C: "Chuyển một chuỗi thành số thực",
    D: "Chuyển một số nguyên thành một chuỗi",
    answer: "B",
  },
  {
    id: 8,
    question: "Trong Javascript hàm parseFloat() dùng để làm gì?",
    A: "Chuyển một chuỗi thành số",
    B: "Chuyển một chuỗi thành số thực",
    C: "Chuyển một chuỗi thành số nguyên",
    D: "Chuyển một số nguyên thành một chuỗi",
    answer: "B",
  },
  {
    id: 9,
    question: "Lệnh prompt trong Javascript để làm gì?",
    A: "Hiện một thông báo nhập thông tin",
    B: "Hiện một thông báo dạng yes, No",
    C: "Cả hai dạng trên",
    D: "Không có lệnh nào đúng",
    answer: "A",
  },
  {
    id: 10,
    question: "Trong Javascript sự kiện Onload thực hiện khi:",
    A: "Khi bắt đầu chương trình chạy",
    B: "Khi click chuột",
    C: "Khi kết thúc một chương trình",
    D: "Khi di chuyển chuột qua.",
    answer: "A",
  },
  {
    id: 11,
    question: "Trong Javascript sự kiện OnUnload thực hiện khi nào?",
    A: "Khi bắt đầu chương trình chạy",
    B: "Khi click chuột",
    C: "Khi kết thúc một chương trình",
    D: "Khi di chuyển chuột qua.",
    answer: "C",
  },
  {
    id: 12,
    question: "Trong Javascript sự kiện Onblur thực hiện khi nào?",
    A: "Khi một đối tượng trong form mất focus",
    B: "Khi một đối tượng trong form có focus",
    C: "Khi di chuyển con chuột qua form",
    D: "Khi click chuột vào nút lệnh",
    answer: "A",
  },
  {
    id: 13,
    question: "Trong Javascript sự kiện OnMouseOver thực hiện khi nào?",
    A: "Khi một đối tượng trong form mất focus.",
    B: "Khi một đối tượng trong form có focus",
    C: "Khi di chuyển con chuột qua một đối tượng trong form.",
    D: "Khi click chuột vào nút lệnh",
    answer: "C",
  },
  {
    id: 14,
    question: "Trong Javascript sự kiện Onclick thực hiện khi nào?",
    A: "Khi một đối tượng trong form mất focus.",
    B: "Khi một đối tượng trong form có focus",
    C: "Khi click chuột vào một đối tượng trong form.",
    D: "Khi click chuột vào nút lệnh",
    answer: "C",
  },
  {
    id: 15,
    question:
      '<\r\nscript >\r\n    function kiemtra() {\r\n        window.open("http://www.vnn.vn", "Chao");\r\n    } <\r\n    /script> < /\r\n    head > <\r\n    body onload = "kiemtra()" > < /body>\r\n\r\nTrong Javascript đoạn mã sau cho ra kết quả gì?',
    A: "Khi chạy thì một trang khác (VNN) được hiện ra .",
    B: "Không chạy được vì sai",
    C: "Khi kết thúc thì một site khác hiện ra",
    D: "Hiện một trang vnn duy nhất.",
    answer: "A",
  },
  {
    id: 16,
    question: "Thẻ <input type=”text” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một ô password",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "A",
  },
  {
    id: 17,
    question: "Thẻ <input type=”Password” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một ô password",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "B",
  },
  {
    id: 18,
    question: "Thẻ <textarea rows= cols = …></texterea> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một ô password",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "C",
  },
  {
    id: 19,
    question: "Thẻ <input type=”Submit” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một nút lệnh dùng để gửi tin trong form đi",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "C",
  },
  {
    id: 20,
    question: "Thẻ <input type=”Radio” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một nhóm đối tượng chọn nhưng chọn duy nhất",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "B",
  },
  {
    id: 21,
    question: "Thẻ <input type=”checkbox” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một nhóm đối tượng chọn được nhiều đối tượng",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "B",
  },
  {
    id: 22,
    question: "Thẻ <input type=”button” …> dùng để làm gì?",
    A: "Tạo một ô text để nhập dữ liệu",
    B: "Tạo một nút lệnh lên trên form",
    C: "Tạo một cùng có nhiều cột nhiều dòng",
    D: "Tất cả các ý trên",
    answer: "B",
  },
  {
    id: 23,
    question: "Lệnh lặp for có dạng như thế nào?",
    A: "For ( biến = Giá trị đầu, Điều kiện, Giá trị tăng)",
    B: "For ( biến = Giá trị đầu, Giá trị tăng, điều kiện)",
    C: "For ( biến = Điều kiện, Giá trị tăng Giá trị cuối)",
    D: "Tất cả các dạng trên.",
    answer: "A",
  },
  {
    id: 24,
    question: "Vòng lặp While là dạng vòng lặp?",
    A: "Không xác định và xét điều kiện rồi mới lặp",
    B: "Không xác định và lặp rồi mới xét điều kiện",
    C: "Cả hai dạng trên",
    D: "Không tồn tại dạng nào ở trên.",
    answer: "A",
  },
  {
    id: 25,
    question: "Vòng lặp (Do.. while) là dạng vòng lặp?",
    A: "Không xác định và xét điều kiện rồi mới lặp",
    B: "Không xác định và lặp rồi mới xét đ-iều kiện",
    C: "Cả hai dạng trên",
    D: "Không có dạng nào.",
    answer: "B",
  },
  {
    id: 26,
    question: "Lệnh break kết hợp với vòng for dùng để?",
    A: "Ngưng vòng for nếu gặp lệnh này",
    B: "Không có ý nghĩa trong vòng lặp",
    C: "Nhảy đến một tập lệnh khác",
    D: "Không thể kết hợp được.",
    answer: "A",
  },
  {
    id: 27,
    question: "Hàm alert() dùng để làm gì?",
    A: "Dùng để hiện một thông báo.",
    B: "Dùng để hiện một thông báo nhập",
    C: "Dùng để chuyển đổi số sang chữ",
    D: "Tất cả các dạng trên.",
    answer: "A",
  },
  {
    id: 28,
    question: "Thẻ <Frameset cols> </frameset>",
    A: "Dùng để chia trang web ra nhiều phần theo cột",
    B: "Dùng để chia trang web ra nhiều phần theo dòng",
    C: "Tất cả dạng trên",
    D: "Không có ý nào ở trên.",
    answer: "A",
  },
  {
    id: 29,
    question: "Thẻ <Frameset rows > </frameset>",
    A: "Dùng để chia trang web ra nhiều phần theo cột",
    B: "Dùng để chia trang web ra nhiều phần theo dòng",
    C: "Tất cả dạng trên",
    D: "Không có ý nào ở trên.",
    answer: "B",
  },
  {
    id: 30,
    question: "Thẻ <Frame src=” duong dan ”>",
    A: "Dùng để chèn ảnh",
    B: "Dùng để lấy dữ liệu từ một trang khác",
    C: "Tất cả dạng trên",
    D: "Không có ý nào ở trên.",
    answer: "C",
  },
  {
    id: 31,
    question:
      "Trong JavaScript sự kiện OnMouseOver xảy ra khi nào trong các trường hợp sau.",
    A: "Khi di chuyển con chuột qua một đối tượng trong form",
    B: "Khi một đối tượng trong form nhận focus",
    C: "Khi một đối tượng trong form mất focus",
    D: "Khi kích chuột vào nút lệnh",
    answer: "A",
  },
  {
    id: 32,
    question: "Cách nào để thêm một comment nhiều dòng trong JavaScript?",
    A: "/*Đây là một comment trên nhiều dòng*/",
    B: "//Đây là một comment trên nhiều dòng//",
    C: "<!--Đây là một comment trên nhiều dòng-->",
    D: "Cả A, B, C đều đúng",
    answer: "A",
  },
  {
    id: 33,
    question:
      "Trong JavaScript sự kiện Onchange xảy ra khi nào trong các trường hợp sau.",
    A: "Khi một đối tượng trong form mất focus",
    B: "Khi kích chuột vào nút lệnh",
    C: "Xảy ra khi giá trị của một trường trong form được người dùng thay đổi dữ liệu",
    D: "Khi một đối tượng trong form nhận focus",
    answer: "C",
  },
  {
    id: 34,
    question: "Làm cách nào để gọi một hàm myFunction trong JavaScript?",
    A: "call function myFunction()",
    B: "call myFunction()",
    C: "myFunction()",
    D: "Cả A, B, C đều đúng",
    answer: "C",
  },
  {
    id: 35,
    question: "Nơi bạn có thể đặt code JavaScript trong trang web?",
    A: "Bạn có thể đặt trong phần <head> hoặc <body>",
    B: "Chỉ trong phần <head>",
    C: "Chỉ trong phần <head>",
    D: null,
    answer: "A",
  },
  {
    id: 36,
    question: "Cách khai báo mảng nào trong JavaScript là đúng?",
    A: 'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")',
    B: 'var colors = ["red", "green", "blue"]',
    C: 'var colors = (1:"red", 2:"green", 3:"blue")',
    D: 'var colors = "red", "green", "blue"',
    answer: "B",
  },
  {
    id: 37,
    question: "Có những cách nào viết code JavaScript để chạy trong trang web?",
    A: "Viết chung với HTML",
    B: "Không thuộc dạng nào",
    C: "Cả hai dạng viết tệp riêng hoặc viết trong trang HTML",
    D: "Viết trên một tệp riêng",
    answer: "C",
  },
  {
    id: 38,
    question: "Cách nào tạo một hàm trong JavaScript?",
    A: "function:myFunction()",
    B: "function = myFunction()",
    C: "function myFunction()",
    D: "Cả A, B, C đều đúng",
    answer: "C",
  },
  {
    id: 39,
    question: "Hàm prompt(…) trong JavaScript dùng để làm gì?",
    A: "Hiển thị thông báo nhập thông tin",
    B: "Hiển thị một thông báo Yes, No",
    C: "Cả hai dạng trên",
    D: "Không phương án nào đúng",
    answer: "A",
  },
  {
    id: 40,
    question:
      "Câu lệnh nào đúng thực hiện việc gọi một script từ bên ngoài có tên là xxx.js?",
    A: '<script src="xxx.js"></script>',
    B: '<script name="xxx.js"></script>',
    C: '<script href="xxx.js"></script>',
    D: null,
    answer: "A",
  },
  {
    id: 41,
    question: "JavaScript là ngôn ngữ kịch bản có che dấu được mã nguồn không?",
    A: "Dấu được vì chương trình hoạt động độc lập với trình duyệt",
    B: "Tùy thuộc vào JavaScript được code ở client hay server",
    C: "Hai phát biểu trên đều sai",
    D: "Hai phát biểu trên đều đúng",
    answer: "B",
  },
  {
    id: 42,
    question:
      "Dùng cách nào có thể biết được trình duyệt đang được sử dụng tại máy client?",
    A: "browser.name",
    B: "client.navName",
    C: "navigator.appName",
    D: null,
    answer: "C",
  },
  {
    id: 43,
    question:
      "Sự kiện nào xảy ra khi người dùng kích vào một phần tử HTML trên trang?",
    A: "onclick",
    B: "onmouseover",
    C: "onchange",
    D: "onmouseclick",
    answer: "A",
  },
  {
    id: 44,
    question: "Trong JavaScript sự kiện Onload xảy ra khi nào?",
    A: "Khi bắt đầu chạy chương trình",
    B: "Khi click chuột",
    C: "Khi di chuyển chuột qua",
    D: "Khi kết thúc một chương trình",
    answer: "A",
  },
  {
    id: 45,
    question: "Trong JavaScript sự kiện Onclick xảy ra khi nào?",
    A: "Khi một đối tượng trong form mất focus",
    B: "Khi click chuột vào nút lệnh",
    C: "Khi click chuột vào một đối tượng trong form",
    D: "Khi một đối tượng trong form nhận focus",
    answer: "B",
  },
  {
    id: 46,
    question: "Trong JavaScript sự kiện OnUnload xảy ra khi nào?",
    A: "Khi bắt đầu chạy chương trình",
    B: "Khi kết thúc một chương trình",
    C: "Khi kết thúc một chương trình",
    D: "Khi di chuyển chuột qua",
    answer: "B",
  },
  {
    id: 47,
    question: "Câu lệnh nào khai báo một biến trong JavaScript?",
    A: "v carName;",
    B: "var carName;",
    C: "variable carName;",
    D: null,
    answer: "B",
  },
  {
    id: 48,
    question: "Ngôn ngữ JavaScript có phân biệt chữ hoa, chữ thường?",
    A: "Có",
    B: "Không",
    C: null,
    D: null,
    answer: "A",
  },
  {
    id: 49,
    question: "Cách viết câu lệnh IF nào sau đây là đúng?",
    A: "if i = 5 then",
    B: "if (i == 5)",
    C: "if i == 5 then",
    D: "if i = 5",
    answer: "B",
  },
  {
    id: 50,
    question:
      "Cách nào để làm tròn 7.25 tới số nguyên gần nhất trong JavaScript?",
    A: "rnd(7.25)",
    B: "round(7.25)",
    C: "Math.round(7.25)",
    D: "Math.rnd(7.25)",
    answer: "C",
  },
  {
    id: 51,
    question: "Câu lệnh lặp For trong JavaScript có dạng nào sau đây?",
    A: "for (biến = Giá trị đầu; Điều kiện; Giá trị tăng)",
    B: "for (biến = Giá trị đầu; Giá trị tăng; điều kiện)",
    C: "for (biến = Điều kiện; Giá trị tăng; Giá trị cuối)",
    D: "Tất cả các dạng trên",
    answer: "A",
  },
  {
    id: 52,
    question:
      "Thực hiện kiểm tra nếu biến i không bằng 5, câu lệnh nào là đúng?",
    A: "if (i != 5)",
    B: "if i =! 5 then",
    C: "if i <> 5",
    D: "if (i <> 5)",
    answer: "A",
  },
  {
    id: 53,
    question:
      "var a = [1, 2, 3];\r\nvar b = [1, 2, 3];\r\nvar c = '1,2,3';\r\n\r\nconsole.log(a == c);\r\nconsole.log(b == c);\r\nconsole.log(a == b);\r\n\r\nKết quả của đoạn code sau là:",
    A: "true, true, false",
    B: "true, true, true",
    C: "true, false, false",
    D: "false, false false",
    answer: "A",
  },
  {
    id: 54,
    question:
      "var a = [9];\r\nvar b = [10];\r\n\r\nconsole.log(a == 9);\r\nconsole.log(b == 10);\r\nconsole.log(a < b);\r\n\r\nKết quả đoạn code sau là:",
    A: "true true true",
    B: "false false false",
    C: "true true false",
    D: "false false true",
    answer: "C",
  },
  {
    id: 55,
    question:
      "let i = 0;\r\n\r\nconst arr = new Array(5);\r\narr.forEach(() => i++);\r\n\r\nconsole.log(i);\r\n \r\n\r\nKết quả của đoạn code sau là:",
    A: 0,
    B: 1,
    C: 4,
    D: 5,
    answer: "A",
  },
  {
    id: 56,
    question:
      "function greatestNumberInArray(arr) {\r\n  let greatest = 0;\r\n  for (let i = 0; i < arr.length; i++) {\r\n    if (greatest < arr[i]) {\r\n      greatest = arr[i];\r\n    }\r\n  }\r\n  return greatest;\r\n}\r\n \r\n\r\nHàm greatestNumberInArray dưới đây có get được phần tử lớn nhất cho mọi array không?",
    A: "Yes",
    B: "No",
    C: null,
    D: null,
    answer: "B",
  },
  {
    id: 57,
    question:
      "const arr = [1, 2, 3];\r\n\r\nconst a = arr.reduce(\r\n  (acc, el, i) => ({ ...acc, [el]: i }),\r\n  {}\r\n);\r\n\r\nconst b = {};\r\nfor (let i = 0; i < arr.length; i++) {\r\n  b[arr[i]] = i;\r\n}\r\n \r\n\r\nHai cách a và b dưới đây đều trả về một object có cùng thuộc tính và giá trị. Theo bạn thì cách nào tối ưu hơn?",
    A: "a",
    B: "b",
    C: null,
    D: null,
    answer: "B",
  },
  {
    id: 58,
    question:
      "const arr = [\r\n  x => x * 1,\r\n  x => x * 2,\r\n  x => x * 3,\r\n  x => x * 4\r\n];\r\n\r\nconsole.log(arr.reduce((agg, el) => agg + el(agg), 1));\r\n \r\n\r\nKết quả là:",
    A: 1,
    B: 60,
    C: 100,
    D: 120,
    answer: "D",
  },
  {
    id: 59,
    question:
      "const ar = [5, 1, 3, 7, 25];\r\nconst ar1 = ar;\r\nconsole.log(ar1.sort());\r\n([5, 25].indexOf(ar[1]) != -1 &&\r\n\tconsole.log(ar.reverse())) ||\r\n(ar[3] == 25 && console.log(ar));\r\nconsole.log(ar1);\r\n \r\n\r\nCho đoạn code sau. Kết quả là:",
    A: "[1, 3, 5, 7, 25] [7, 5, 3, 25, 1] [1, 25, 3, 5, 7] [1, 25, 3, 5, 7]",
    B: "[1, 25, 3, 5, 7] [5,1,3,7,25]",
    C: "[1, 25, 3, 5, 7] [7, 5, 3, 25, 1] [7, 5, 3, 25, 1] [7, 5, 3, 25, 1]",
    D: "An error is thrown",
    answer: "C",
  },
  {
    id: 60,
    question:
      "const arr1 = ['a', 'b', 'c'];\r\nconst arr2 = ['b', 'c', 'a'];\r\n\r\nconsole.log(\r\n  arr1.sort() === arr1,\r\n  arr2.sort() == arr2,\r\n  arr1.sort() === arr2.sort()\r\n);\r\n \r\n\r\nCho đoạn code sau. Kết quả là:",
    A: "true true true",
    B: "true true false",
    C: "false false false",
    D: "true false true",
    answer: "B",
  },
  {
    id: 61,
    question:
      "function ArrayBoolean() {\r\n  if ([] == true && [1] == true) return [true, true];\r\n  else if ([] == true && [1] == false) return [true, false];\r\n  else if ([] == false && [1] == true) return [false, true];\r\n  else return [false, false];\r\n}\r\nArrayBoolean();\r\n \r\n\r\nCho đoạn code sau. Kết quả là:",
    A: "[true, true]",
    B: "[true, false]",
    C: "[false, true]",
    D: "[false, false]",
    answer: "C",
  },
  {
    id: 62,
    question:
      "let dog = {\r\n  breed: 'Border Collie',\r\n  sound: 'Wooh',\r\n  getBreed: () => {\r\n    return this.breed;\r\n  },\r\n  getSound: function() {\r\n    return this.sound;\r\n  }\r\n};\r\nconsole.log(dog.getBreed(), dog.getSound());\r\n \r\n\r\nCho đoạn code sau. Kết quả là:",
    A: "Border Collie, Wooh",
    B: "Border Collie, undefined",
    C: "undefined, Wooh",
    D: "undefined, undefined",
    answer: "C",
  },
  {
    id: 63,
    question:
      "const person = { name: 'duthaho' };\r\n\r\nfunction sayHi(age) {\r\n  return `${this.name} is ${age}`;\r\n}\r\n\r\nconsole.log(sayHi.call(person, 69));\r\nconsole.log(sayHi.bind(person, 69));\r\n \r\n\r\nĐoạn code sau sẽ cho kết quả như thế nào?",
    A: "undefined is 69 duthaho is 69",
    B: "function function",
    C: "duthaho is 69 duthaho is 69",
    D: "duthaho is 69 function",
    answer: "D",
  },
  {
    id: 64,
    question:
      "function withVar() {\r\n  const b = () => a;\r\n  var a = 24;\r\n  return b;\r\n}\r\n\r\nfunction withLet() {\r\n  const b = () => a;\r\n  let a = 24;\r\n  return b;\r\n}\r\n\r\nfunction changingValue() {\r\n  let a = 24;\r\n  const b = () => a;\r\n  a = 42;\r\n  return b;\r\n}\r\n\r\nconsole.log(withVar()()); // ??\r\nconsole.log(withLet()()); // ??\r\nconsole.log(changingValue()()); // ??\r\n \r\n\r\nKết quả đoạn code sau là:",
    A: "undefined Error 42",
    B: "24 Error 24",
    C: "24 24 42",
    D: "undefined Error 24",
    answer: "C",
  },
  {
    id: 65,
    question:
      "let a = new Date('2019,1,1').toLocaleDateString();\r\nlet b = new Date(2019, 1, 1).toLocaleDateString();\r\nconsole.log(a, b);\r\n \r\n\r\nKết quả đoạn code sau là?",
    A: "1/1/2019 2/1/2019",
    B: "1/1/2019 1/1/2019",
    C: null,
    D: null,
    answer: "A",
  },
  {
    id: 66,
    question: "console.log(fetch);\r\n \r\n\r\nKết quả của câu lệnh sau:",
    A: "The fetch function",
    B: "A reference error",
    C: "It depends",
    D: null,
    answer: "C",
  },
  {
    id: 67,
    question:
      "const a = 0.1;\r\nconst b = 0.2;\r\nconst c = 0.3;\r\n\r\nconsole.log(a + b === c);\r\n \r\n\r\nCho đoạn code sau, kết quả là:",
    A: true,
    B: "Fase",
    C: null,
    D: null,
    answer: "B",
  },
  {
    id: 68,
    question:
      "function Person(firstName, lastName) {\r\n  this.firstName = firstName;\r\n  this.lastName = lastName;\r\n}\r\n\r\nconst ti = new Person('du', 'ti');\r\nconst teo = Person('du', 'teo');\r\n\r\nconsole.log(ti);\r\nconsole.log(teo);\r\n \r\n\r\nĐoạn code sau sẽ có kết quả là:",
    A: 'Person {firstName: "du", lastName: "ti"} undefined',
    B: 'Person {firstName: "du", lastName: "ti"} Person {firstName: "du", lastName:"teo"}\'',
    C: 'Person {firstName: "du", lastName: "ti"} {}',
    D: 'Person {firstName: "du", lastName: "ti"} ReferenceError',
    answer: "A",
  },
  {
    id: 69,
    question:
      "function sayHi() {\r\n  return (() => 0)();\r\n}\r\n\r\nconsole.log(typeof sayHi());\r\n \r\n\r\nCho đoạn code sau, kết quả là:",
    A: "object",
    B: "number",
    C: "function",
    D: "undefined",
    answer: "B",
  },
  {
    id: 70,
    question:
      "const notifications = 1\r\n\r\nconsole.log(\r\n  `You have ${notifications} notification${notifications !==\r\n    1 && 's'}`\r\n) \r\n \r\n\r\nĐoạn code trên sẽ có kết quả là:",
    A: "You have 1 notification",
    B: "You have 1 notifications",
    C: "You have 1 notificationfalse",
    D: null,
    answer: "C",
  },
]
